#!/bin/sh

sxhkd &
bar2 &
nitrogen --random --set-zoom-fill &
redshift &
autocutsel &
dunst &
wmname LG3D &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          15
bspc config top_padding         20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config click_to_focus       true
bspc config pointer_follows_focus false

bspc config focused_border_color '#939393'
bspc config normal_border_color  '#939393'

# bspc config focused_border_color '#EEEEEE'
# bspc config normal_border_color  '#EEEEEE'

bspc rule -a firefox desktop='^2'
bspc rule -a mpv desktop='^3'
bspc rule -a scrcpy desktop='^3'
bspc rule -a qemu-system-x86_64 state=floating
